name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Replace environment variables
        run: |
          sed -i "s|SUPABASE_URL|${{ secrets.SUPABASE_URL }}|g" src/environments/environment.production.ts
          sed -i "s|SUPABASE_ANON_KEY|${{ secrets.SUPABASE_ANON_KEY }}|g" src/environments/environment.production.ts

      - name: Build Angular app
        run: npm run build -- --configuration=production --base-href=/your-repo-name/

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run deploy-ghpage
